<?php

/**
 * @file
 * Contains site_plus_util.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function site_plus_util_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the site_plus_util module.
    case 'help.page.site_plus_util':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Site plus utilities') . '</p>';
      return $output;

    default:
  }
}
